project:
  type: book

book:
  title: "愛自然(iNaturalist)說明文件"
  author: "Cheng-Tao Lin, Yu-Ting He, Chu-Chia Kuo, Li-Yue Wu"
  favicon: images/inattw.png
  page-navigation: true
  language: zh
  number-depth: 2
  repo-url: https://github.com/iNaturalistTaiwan/iNatTWDocs
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub, docx]
  sharing: [facebook, twitter]
  date: "2022-07-20"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
		code-copy: true
		fig-responsive: true
		citations-hover: true
		comment-hover: true
  pdf:
		header-includes:
    - \usepackage{fontspec} # 使用 fontspec package
    - \usepackage{xeCJK}    # 使用 xeCJK package
    - \setCJKmainfont{Songti TC}
		documentclass: scrreprt

